image: "python:3.6"

before_script:
  - python --version
  - pip install pipenv
  - pipenv install --dev

stages:
  - Test

unit_test:
  stage: Test
  script:
  - pipenv run python -m pytest -v --ignore=ptools-python
