image: "python:3.12"

before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.galaxy.ibpc.fr/".insteadOf "https://gitlab.galaxy.ibpc.fr/"
  - git submodule sync && git submodule update --init
  - python --version
  - pip install pipenv
  - pipenv install --dev
  - pipenv install numpy scipy PyYAML #should be automatically done within ptools-python but fails on CI

stages:
  - Test

unit_test:
  stage: Test
  script:
  - pipenv run python -m pytest -v --ignore=ptools-python
